export const UPDATE_COLUMN = "UPDATE_COLUMN";
export const UPDATE_ROW = "UPDATE_ROW";
export const UPDATE_CELL = "UPDATE_CELL";
export const UPDATE_MATRIX = "UPDATE_MATRIX";
export const UPDATE_SUMHOVERED = "UPDATE_SUMHOVERED";
export const UPDATE_ITEMHOVERED = "UPDATE_ITEMHOVERED";
